name: play5
version: 1.0.0+1
description: Play5 - 5-a-side football booking and team-matching app
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  collection: ^1.18.0
  uuid: ^4.4.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.2
  cloud_firestore: ^4.14.1
  firebase_messaging: ^14.7.7
  animations: ^2.0.8
  flutter_local_notifications: ^17.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/l10n/
